# Input Settings: initialize base input folder names, and interactomes,
# pathway collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that interactomes should be placed into 
    interactome_dir: "interactomes"

    # Subdirectory of inputs that pathway collections should be placed into
    pathway_collection_dir: "interactions"

    # Denotes a list of interactomes, each with the following parameters:
    #   name: Name of the interactome. May be used in logging or other 
    #       messages written during execution
    #
    #   filename: Filename of the interactome
    #
    #   edge_dir_file: a file containing whether or not each edge is
    #       directed or undirected in the interactome
    #
    #   path: Subdirectory of interactome_dir, specified by list of folders
    #       along the path 
    interactomes:

        - name: "no-kegg-no-spike"
          filename: "2018-05-02-human-ppi-weighted.txt"
          edge_dir_file: "2018-05-02-human-ppi-weighted-directions.txt"
          path: ["human"]

    # Denotes a list of pathway collections, each with the following 
    # parameters:
    #   name: Name of the interactome. May be used in logging or other 
    #       messages written during execution
    #
    #   path: Subdirectory of pathway_collection_dir, where the node and edge
    #       files corresponding to a pathway collection's pathways should be
    #       placed
    #
    #   pathways: List of pathways in the collection. The name used here will
    #       be used by the pipeline to identify corresponding pathway nodes and
    #       edges files in the subdirectory specified above by the path
    #       parameter. Specifically, the pipeline expects to find files
    #       <name>-nodes.txt and <name>-edges.txt in that folder.
    #
    pathway_collections:
        - name: "netpath-s-t-pruned"
          path: ["netpath-s-t-pruned-extra-filtering", "pathways"]
          pathways:
            #- "BDNF"
            #- "EGFR1"
            #- "IL1"
            #- "IL2"
            #- "IL3"
            #- "IL6"
            #- "IL-7"
            #- "KitReceptor"
            #- "Leptin"
            #- "Prolactin"
            #- "RANKL"
            #- "TCR"
            #- "TGF_beta_Receptor"
            #- "TNFalpha"
            - "Wnt"

    # Denotes a list of algorithms to run. Each has the following parameters: 
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   <additional parameters>: any additional, algorithm-specific parameters 
    #       should be specified in the map for a given algorithm
    algorithms:

        #- name: "ZeroQuickLinkerLabelNegatives"
        #  params: {}

        #- name: "GenInduced"
        #  params: {}

        #- name: "GenInducedRWER"
        #  params:
        #    q: [.1667]

        #- name: "GeneralizedShortcutsSSViaRWRFlux"
        #  params:
        #    alpha: [1.0]
        #    k: [1000]
        #    q: [.1667]

        #- name: "GeneralizedShortcuts"
        #  params:
        #    alpha: [1.0]
        #    k: [1000]

        #- name: "RegLinker"
        #  params: 
        #    rlcs:
        #        #- ["one-x", ["p*xp*"]] 
        #        #- ["one-then-two-x", ["p*xp*", "p*xp*xp*"]]
        #        - ["one-then-two-then-three-x", ["p*xp*", "p*xp*xp*", "p*xp*xp*xp*"]]
        #        #- ["xx", ["p*xxp*"]]
        #        - ["xx-xxx", ["p*xxp*", "p*xxxp*"]]
        #        #- ["xx-xxx-xxxx", ["p*xxp*", "p*xxxp*", "p*xxxxp*"]]
        #        #- ["xx-xxx-xxxx-xxxxx", ["p*xxp*", "p*xxxp*", "p*xxxxp*", "p*xxxxxp*"]]
        #        #- ["consecutive-x-extra", ["p*xxp*(xp*)*"]]

        - name: "RegLinkerRWER"
          params: 
            rlcs:
                #- ["one-x", ["p*xp*"]]
                #- ["one-then-two-x", ["p*xp*", "p*xp*xp*"]]
                #- ["one-then-two-then-three-x", ["p*xp*", "p*xp*xp*", "p*xp*xp*xp*"]]
                #- ["two-then-three-x", ["p*xp*xp*", "p*xp*xp*xp*"]]
                - ["two-x", ["p*xxp*"]]
                #- ["1234", ["p*xp*", "p*xp*xp*", "p*xp*xp*xp*", "p*xp*xp*xp*xp*"]]
                #- ["xx", ["p*xxp*"]]
                #- ["xx-xxx", ["p*xxp*", "p*xxxp*"]]
                #- ["xx-xxx-xxxx", ["p*xxp*", "p*xxxp*", "p*xxxxp*"]]
                #- ["xx-xxx-xxxx-xxxxx", ["p*xxp*", "p*xxxp*", "p*xxxxp*", "p*xxxxxp*"]]
                #- ["consecutive-x-extra", ["p*xxp*(xp*)*"]]
            q:
                - .1667


# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
