* Log

** June 20, 2018
- Okay, I'm reverting the re-naming decision I made on January 9th (see 
  log entry for that date). It'll be easier to eliminate bad nodes if they
  all are consistently named.

  Anna mentioned over email that there is a possibility of blank nodes,
  but I've never seen that. Attempting to grep for empty lines in the node
  columns of node files and the tail/head columns of edge files did not 
  reveal anything.

- On another note, it looks like the S-T pruning pretty much eliminates all
  of the junk nodes anyway. So, I'm not going to bother trying to add a
  separate step for that right now.


** June 19, 2018
- Okay, there is a lot to think about when it comes to S-T pruning and
  creating the interactome and directed-trumps-undirected, etc.

  - I recently found out that in my original pipeline, I S-T pruned
    before removing edges in the pathway that are not in the interactome.
    In practice, this means that I could still be evaluating edges as 
    positives that were unreachable by RegLinker.
        - This can be alleviated with an additional pre-processing step, 
          before S-T pruning, on the pathways. This is still NOT done 
          automatically in the pipeline.

  - A similar problem arises when we consider trying to separate directed and
    undirected edges.
        - In order to do this, we need an evidence file that has every edge.

        - Previously, I decided to include every edge from pathways in that
          evidence file; the pathways were not a subset of the interactome to
          begin with, and this would fix that problem.

        - That said, I did not fully consider this decision. I will do that
          now. Potential complications stem from the interaction between
          S-T pruning and having directed edges trumping undirected edges.

        - One question: should I add NetPath pathway edges to evidence if they
          are going to be pruned?
            - Either way, I don't count the pruned edges as positives
            - However, I could potentially do any/all of the following:
                1) Add an undirected edge to the interactome that winds up
                   getting pruned in the pathway
                    - This will now currently be counted as a negative,
                      which seems wrong.

                2) Add a directed edge to the interactome that winds up 
                   getting pruned in the pathway
                    - See above

                3) Supercede an undirected edge in the interactome with a
                   directed edge from the pathway that then gets pruned
                    - Technically, we lose a negative in this case.

        - But the opposite approach has problems too! We could instead use the
          base evidence file to filter out nodes (currently doing that now) and
          edges
            - That could remove a lot of pathway edges. Especially in the case
              of NetPath + 2018 PathLinker interactome, which uses different
              NetPath edges.  This is why I add the pathway to the evidence
              file in the first place!

        - It all really boils down to whether the pathways should be included
          in the evidence or not. It complicates things that the NetPath
          pathways we are using for evaluation are not included in our
          interactome build scripts.

        - The only real decision is to make sure the pathways are included
          in the evidence because otherwise the 2018 interactome decimates
          the NetPath pathways during filtering. 

        - The evidence file is not really a problem either.
            - If a NetPath edge is directed, then adding it to the evidence
              file before pruning would only remove an undirected edge from the
              NetPath pathways.

            - If a NetPath edge is undirected, then it will stay undirected 
              unless the evidence file trumps it.

        - So, there's only one real issue, and it comes down to S-T pruning
          again (the negatives issues detailed above). If I'm adding the 
          NetPath pathways to the evidence file, it doesn't hurt to use that
          file to trump undir edges in the pathway itself.

        - So what we can do is the following:
            - Add all of the edges from a pathway to the evidence file

            - Determine directions of every edge using evidence file

            - Use this information to filter edges from the pathway
                - Note that this filtering includes all pathway directed edges,
                  so it is the most generous things can possibly be for the
                  pathway in terms of it keeping its edges

                - It's also as strict a filtering as can possibly be applied
                  by the rest of the interactome.

            - S-T prune. Any undirected edges that would be deleted by 
              directed edges from the rest of the interactome will have been
              deleted, which is what we want.
            
            - Add surviving edges to fresh copy of the original evidence 
              file. 


** May 14, 2018
- I found that Q13547 is both listed as a transcription factor and not a
  transcription factor for TGF Beta. I'm going to remove the line that
  says it is not a TF.


** May 7, 2018
- Is it a problem that we are using RWER to determine the edge direction of 
  undirected edges, and then comparing RWER and RWR on an interactome with
  directions determined by RWER?
    - Aditya doesn't think so, claiming that it is a pre-processing step and
      what's important is giving the same input to all algorithms, which is
      a fair point. I'm just worried that we could be giving biased input. 

    - I'm going to try and see how many directions disagree if I use one
      versus the other. If it's a small number, then I won't worry about it.
      If it is a large number, I'll start to be more concerned.

- The question also arises: what restart probability should be used when 
  determining direction?


** May 6, 2018
- Current plan for pathway, interactome, and interactome edge direction file 
  creation:
    - 1) Take the intersection of the pathway nodes and the evidence file 
         nodes to get filtered nodes and edges file per pathway
         - This eliminates dumb nodes like "-" and "--" and the nodes
           that Jeff says aren't actually UniProt IDs

    - 2) Add the filtered edges file for each pathway to the evidence file

    - 3) S-T prune the filtered edge and node files

    - 4) Build an interactome using the new evidence file

    - 5) Build a list of directions for each edge in the interactome using
         the evidence file

    - This procedure has the added advantage of not needing a "directions"
      file per pathway

    - This allows pathway edge direction to trump interactome edges, and
      vice versa

    - This will not consider edges that are a part of the pathway but whose
      nodes are not a part of the pathway.


** May 3, 2018
- We recently came to the conclusion that I have been treating interactome
  and pathway edges as directed incorrectly. The problem is that all edges
  are seen as directed edges at present (undirected edges are converted to
  two directed edges). Thus, it is incorrect for me to include one half of
  an undirected edge's directed counterparts in the set of positives and the
  other in a set of negatives

- Thus, I started working on remedying this, by separating directed edges from
  undirected edges until necessary. This provided the impetus to update the
  interactome version we are using, along with the pathways.
    
    - The plan to fix this:
        - 1) Keep, for both a pathway and an interactome, a graph of
             directed edges and graph of undirected edges

        - 2) Create folds using the directed and undirected versions 
             separately

        - 3) Create a directed version of the interactome and use the folds
             to run RWER.

        - 4) The RESULTING and FINAL FOLDS are directed versions of the 
             original folds, except undirected edges only have a single
             direction included (the direction that got the highest flux)

        - To put this another way:
            - I create directed train positives from the pathway
            - I create undirected train positives from the pathway
            - I create directed test positives from the pathway
            - I create undirected test positives from the pathway
                - From these, I create: 
                    - merged pathway positives graph (all edges are directed)
                    - merged pathway negatives graph (all edges are directed)

            - I create directed train negatives from the interactome 
            - I create undirected train negatives from the interactome 
            - I create directed test negatives from the interactome 
            - I create undirected test negatives from the interactome 
                - From these, I create: 
                    - merged interactome positives graph
                    - merged interactome negatives graph

            - Then, I create a merged interactome and run RWER on it using the
              merged train positives from the pathway

            - Then, for each merged graph:
                - Look at the undirected graph that comprised part of its 
                  input
                    - For each edge in this graph, look up the edge flux
                      from the RWER in the merged interactome

                        - Delete the directed edge created from this undirected
                          edge that has the lower flux

            - This results in four merged graphs. These graphs form the 
              input to the algorithms and precision/recall

        - Note that this WOULD prevent us from doing certain edge selection
          techniques. E.g., if we wanted folds based in paths as opposed to the
          selection of individual components. We can separate undirected edges
          from directed edges as long as the fold generation does not need to
          consider the dependencies between the two.

    - Interactome: 
        - I am now using Jeff's 2018_01 version of the interactome. I obtain
          edge directionality (directed or undirected, that is) by looking at
          the interactome's evidence file.
    
    - Pathways:
        - At first, Jeff suggested I extract the NetPath pathways from the 
          interactome's evidence file. I did this first. Note that this does
          NOT take into account that a pathway's undirected edge could
          be trumped by a directed edge from a different evidence source.
            
            - NOTE: TAKING DIRECTIONALITY FROM THE EVIDENCE FILE HAS A 
              HIDDEN DANGER. This is because we do not USE all evidences in
              the interactome itself. This means that if a line in the 
              evidence file lists an edge as directed, the interactome itself
              could still have been built using that edge as UNdirected.
                - I discussed this with Jeff. We noted 71 such cases, from
                  MINT. He decided to just add these edges back to the 
                  interactome.
        
            - When I tried to S-T prune these pathways, I wound up with several
              pathways being absolutely decimated. I realized that I was again
              interpreting the edges in the resulting pathway as directed
              instead of undirected. I then altered the pathway file to include
              both directions explicitly to remedy this, but the results were
              similar: the pathways were decimated

        - Thus, I now turn to the original SBML files once more. The parsed
          versions that I have been using has an edge_type column that I can
          use to determine the directionality.
            - The current plan is to re-parse the parsed "-edges.txt" files
              derived from SBML, then add them to the evidence file,
              then create a new interactome, then use that interactome to 
              inform the directionality of the "-edges.txt" files
            
            - I do not want to have any conflicts between the pathways and
              the interactome in terms of direction. There are four cases: 

                1) NetPath says an edge is directed, interactome agrees 
                2) NetPath says an edge is undirected, interactome agrees 
                3) NetPath says an edge is directed, interactome disagrees
                4) NetPath says an edge is undirected, interactome disagrees

                - The first two cases are not problems. 

                - The third case can be ammeliorated by including the NetPath
                  SBML files in the evidence file and re-weighting the
                  interactome

                - The final case is the annoying one. It's not a terrible
                  problem because I can just say that the resulting fold
                  direction is the one the interactome already has.

                - Either way, I would prefer to start out with the pathway
                  as a strict subset of the interactome.

        - I do not think the S-T pruning should be a problem because if
          one edge in an undirected edge pair is on an S-T path, the other 
          direction has to be as well. 


** March 7, 2018
- After consulting with Murali and Aditya, I removed the second entry for
  P19838 in the EGFR node file (the row that has its type listed as "none").


** February 22, 2018
- QuickLinkerConcat has some subtle errors due to floating point.
  In this algorithm, we combine the results for multiple regular expressions,
  concatenating one set after another. When we aggregate over folds, we
  use the cost/score associated with each row to re-rank the rows, and then
  use the resulting ranked rows to calculate precision/recall. To prioritize
  one regex's results before all the others (even across folds), we add 
  a number to this score for each row before aggregation (for 3 regexes, the
  first gets + 2, the second gets + 1, the third gets + 0).

  By adding to the floating point numbers, due to rounding error, floating
  points numbers that were only very slightly different before the addition
  might get the same rank after the addition. In other words, 1 + x = 1 + y


** February 19, 2018
- I learned today that the node file for EGFR has the same protein
  listed TWICE: that protein is P19838. One row has it as a TF, and
  one has it as none. I am not sure what to do here, and need to ask
  Murali about this. If it is meant to be a TF, it is getting messed 
  up in my pipeline currently, which assumes that each node is listed
  only ONCE in the node file.


** January 24, 2018
- Today, while creating an interactome by adding missing edges from the 
  Netpath pathways, I noticed that, similar to the Kit pathway (see
  January 9) TCR and the TGF_beta_receptor pathway have nodes named "-".
  For now, this is mostly just an annoyance, but it does mean the scripts
  for posting to GraphSpace might be slightly incorrect. 

  I also don't have a good idea of what these nodes are supposed to be.


** January 23
- In our last meeting, we discussed the possibility that we where maybe 
  not thinking our precision/recall calculation through. In particular, each
  fold consists of a list of positives and negatives to train on. However,
  when we run the algorithm all the negatives (those in the fold and those 
  not in the fold) are given the label n (as are the test positives), 
  while the list of training positives are given the label p.

  After discussing for a while, we decided that we would probably not improve
  precision/recall by labeling training edges with a different label, like "x".
  This is 1) because you might need to go through an "x" to get to a "p"
  anyway, and 2) we aren't using the "x"s in the calculation of a particular
  fold anyway.


** January 10, 2018
- I emailed one of the original authors of FAdo asking their thoughts on the
  .tablereg file. 


** January 9, 2018
- I found an edge in the KitReceptor pathway nodes/edges file that Anna used.
  The name of this node was "--" and in the node file, it had no node type.  I
  am changing the name of this node to comply with Jeff's GraphSpace posting
  script, which identifies the nodes in an edge by the delimiting character
  "-".

- I also found a file, .tablereg, which seems to have been left by FAdo.  I did
  a search on Google, and I found a GitHub repository for FAdo. I'm not sure if
  it is the original repository for FAdo or not (pypi would seem to indicate
  otherwise). Regardless, I left an issue:

  https://github.com/Glavin001/FAdo/issues/3

  For now, I am operating under the assumption that this file is not that
  important and shouldn't pose a threat to parallelization. This could be an
  erroneous assumption.

- Update: The author of the repo actually got back to me fairly quickly. While
  he is not the original author, he looked into the code and does believe the
  code could be problematic if parallelized. 


** October 19, 2017
- The old PathLinker script in Anna's directory, by default, divided all edge
  weights by the sum of the weight of all edges. If you think about it, this
  minimizes the any importance of edge weight at all, given the negative log
  transform of edge weights. By removing the depedence of the master script on
  the EXACT version Anna was referencing, I've removed the ability to
  automatically recreate this effect.

  If you want to recreate this parameter, you can now pass a very large value
  for the edge penalty to PathLinker. However, at the moment, the ability to
  pass an edge penalty is not possible in our master script. It might be
  worthwhile to write some sort of JSON config file parser that reads in
  parameters for every algorithm. It's getting to the point where the user is
  absolutely inundated with switches to provide the program.


** September 27, 2017
- I refactored the minimum cut computation in the main PathLinker script. One
  possibly important change is that before, it was only being run if the
  directory did not already exist. I decided to eschew this notion, and always
  recompute it, because we didn't have checks on if the parameters themselves
  were actually changing.

* Pathways
- Consist of node files and edge files

- Node files seem very lightly parsed: you will not infrequently see the same 
  node listed with different properties

- Derived from the SBML files Anna parsed several years ago 

- It would appear, at least on the surface, that both directions of an
  undirected edge are listed. I have not rigorously tested this. Jeff says this
  is the case.

* Interactome
- Both directions of an undirected edge should be listed
